# Set the directory we want to store zinit and plugins
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download zinit, if it's not there yet
if [ ! -d "$ZINIT_HOME" ]; then
	mkdir -p "$(dirname $ZINIT_HOME)"
	git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source/Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# Add in zsh plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab

# Add in snippets
zinit snippet OMZP::git

# Load completions
autoload -U compinit && compinit

zinit cdreplay -q

# OS specific
if [[ "$OSTYPE" == "darwin"* ]]; then
	# brew
	#eval "$(/opt/homebrew/bin/brew shellenv)"

	# python
	#export PATH="$(brew --prefix python)/libexec/bin:$PATH"

	# llvm
	export PATH="$(brew --prefix llvm)/bin:$PATH"

	# miniconda
	# eval "$(conda "shell.$(basename "${SHELL}")" hook)"

	# modular
	# export PATH="$PATH:/Users/dlond/.modular/bin"
	# eval "$(magic completion --shell zsh)"

	# clipboard
	alias clip="pbcopy"

elif [[ "$OSTYPE" == "linux-gnu"* ]] then
	# my tools
	export PATH="$HOME/bin:$PATH"

	# miniconda
	# __conda_setup="$('/local1/dlond/miniforge3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
	# if [ $? -eq 0 ]; then
	# 	eval "$__conda_setup"
	# else
	# 	if [ -f "/local1/dlond/miniforge3/etc/profile.d/conda.sh" ]; then
	# 		. "/local1/dlond/miniforge3/etc/profile.d/conda.sh"
	# 	else
	# 		export PATH="/local1/dlond/miniforge3/bin:$PATH"
	# 	fi
	# fi
	# unset __conda_setup

	# if [ -f "/local1/dlond/miniforge3/etc/profile.d/mamba.sh" ]; then
	# 	. "/local1/dlond/miniforge3/etc/profile.d/mamba.sh"
	# fi

	# clipboard
	alias clip="xclip -selection clipboard"
fi

# Keybindings
bindkey -e
bindkey '^y' autosuggest-accept # or do I just want ^f?
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors '${(s.:.)LS_COLORS}'
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'
setopt globdots

# Shell integrations
export DIRENV_LOG_FORMAT=""

# Aliases
alias tree='tree -C'
alias cat='bat'
alias ls='ls -G'
alias ll='ls -lah'
alias vim='nvim'
alias sf='fzf -m --preview="bat --color=always {}" --bind "ctrl-w:become(nvim {+}),ctrl-y:execute-silent(echo {} | clip)+abort"'
export EDITOR=nvim

# Initialize Oh My Posh
# Check if the command exists before trying to run it
if command -v oh-my-posh > /dev/null; then
  # Use the theme file managed by Home Manager via xdg.configFile
  eval "$(oh-my-posh init zsh --config "${XDG_CONFIG_HOME:-$HOME/.config}/omp/my_catppuccin.toml")"
fi
